/*
Developer Notes — Pointer (JournalApp_DeveloperNotes)
This project’s developer notes are canonicalized at the workspace level.

Canonical location:
- ConicalDeveloperNotes.swift
Locator:
- ConicalDeveloperNotes project (top-level file in that project’s group within the workspace). If missing, add existing file via File > Add Files… and uncheck "Add to targets".

Editing policy:
- Do not edit this file. Make all changes in ConicalDeveloperNotes.swift.
- This pointer exists to help discoverability inside the project tree.

Standing Orders (addendum):
- Do NOT edit, move, add, or change ConicalDeveloperNotes.swift without Michael’s express permission. When in doubt, ask first.

Scope of Notes (summary):
- Workspace-level notes capture cross-project policies and decisions.
- Project-level files may include brief, timestamped "Project Addendum" notes for local, project-only details (e.g., debugging logs, target settings) if needed.
- Keep shared decisions in the canonical file to avoid duplication and drift.

Not Found? Quick Checklist:
- Search for "ConicalDeveloperNotes.swift" in the workspace.
- If the file exists on disk but isn’t visible, add it back to the navigator (File > Add Files…).
- If it’s missing locally, pull latest from git or copy from the other machine.
- As a last resort, ask to "recreate canonical" to restore from the latest known content.

Pointer header last updated: 2025 SEP 20 - 1428 (CT)
*/

