name: iOS Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_16.2.app"

      - name: List schemes (debug aid)
        run: xcodebuild -list -project "Journal App.xcodeproj"

      - name: Build (iOS Simulator)
        run: |
          set -o pipefail
          xcodebuild \
            -project "Journal App.xcodeproj" \
            -scheme "Journal App" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -configuration Debug \
            build | xcpretty
